"""add message embeddings

Revision ID: 9d757d1770ef
Revises: 1dedd46d4684
Create Date: 2026-09-11 18:20:53.146395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9d757d1770ef'
down_revision: Union[str, Sequence[str], None] = '1dedd46d4684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_embeddings_conversation_id'), 'message_embeddings', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_embeddings_message_id'), 'message_embeddings', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_embeddings_message_id'), table_name='message_embeddings')
    op.drop_index(op.f('ix_message_embeddings_conversation_id'), table_name='message_embeddings')
    op.drop_table('message_embeddings')
    # ### end Alembic commands ###
